version: '3.8'

services:
  app:
    container_name: blogapp
    restart: always
    image: blog
    build: .
    ports:
      - 9090:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb

  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - C:\Projects\db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: blog
      MYSQL_ROOT_PASSWORD: root

